import { readFile } from 'node:fs/promises';
import type { Plugin } from 'vite';
import { defineConfig, mergeConfig } from 'vitest/config';
import baseConfig from './vitest.config';

const STRYKER_SETUP_FILE = /(?:^|[/\\])stryker-setup-\d+\.js$/;
const STRYKER_SOURCE_MAP_COMMENT = /\r?\n\/\/# sourceMappingURL=stryker-setup\.js\.map\s*$/;

/**
 * Compatibility shims for setup files generated by Stryker's Vitest runner.
 *
 * Stryker 9.6 copies stryker-setup.js into each sandbox without copying its
 * external source map. Returning it from a Vite load hook prevents Vite from
 * trying to read that nonexistent map.
 */
export function strykerVitestCompatibilityPlugin(): Plugin {
  return {
    name: 'squisq:stryker-vitest-compatibility',
    enforce: 'pre',
    async load(id) {
      const fileName = id.replace(/[?#].*$/, '');
      if (!STRYKER_SETUP_FILE.test(fileName)) return null;

      const code = await readFile(fileName, 'utf8');
      return {
        code: code.replace(STRYKER_SOURCE_MAP_COMMENT, ''),
        map: null,
      };
    },
  };
}

export default mergeConfig(
  baseConfig,
  defineConfig({
    plugins: [strykerVitestCompatibilityPlugin()],
  }),
);
