/**
 * Battle-test corpus: a broad, category-organized set of AI-style ASCII
 * diagrams, each with its intended semantics. Every fixture here is
 * verified to (a) detect as a diagram, (b) parse to exactly these
 * nodes/edges/containers, and (c) survive the render↔parse fixpoint
 * byte-stably. See asciiDiagramBattle.test.ts.
 *
 * GENERATED by scratchpad/gen-battle-fixtures.mjs — edit there and re-run.
 */

export interface BattleDiagram {
  name: string;
  category: string;
  art: string;
  /** Expected node ids (order-independent). */
  nodes: string[];
  /** Expected edges: [source, target, label?, directed?]. directed defaults true. */
  edges: Array<[string, string, (string | undefined)?, boolean?]>;
  /** Expected containment: childId → containerId. */
  containers?: Record<string, string>;
}

export const BATTLE_DIAGRAMS: BattleDiagram[] = [
  {
    name: 'linearEtl',
    category: 'linear',
    art: `┌─────────┐     ┌───────────┐     ┌──────────┐
│ Extract │ ──> │ Transform │ ──> │   Load   │
└─────────┘     └───────────┘     └──────────┘`,
    nodes: ['extract', 'transform', 'load'],
    edges: [
      ['extract', 'transform'],
      ['transform', 'load'],
    ],
  },
  {
    name: 'requestLifecycle',
    category: 'linear',
    art: `┌────────┐    ┌───────────────┐    ┌─────────┐    ┌──────────┐
│ Client │───>│ Load Balancer │───>│   API   │───>│ Database │
└────────┘    └───────────────┘    └─────────┘    └──────────┘`,
    nodes: ['client', 'load-balancer', 'api', 'database'],
    edges: [
      ['client', 'load-balancer'],
      ['load-balancer', 'api'],
      ['api', 'database'],
    ],
  },
  {
    name: 'deployPipelineAscii',
    category: 'linear',
    art: `+-------+     +------+     +-------+     +--------+
| Build | --> | Test | --> | Stage | --> | Deploy |
+-------+     +------+     +-------+     +--------+`,
    nodes: ['build', 'test', 'stage', 'deploy'],
    edges: [
      ['build', 'test'],
      ['test', 'stage'],
      ['stage', 'deploy'],
    ],
  },
  {
    name: 'mlPipeline',
    category: 'linear',
    art: `┌──────────┐   ┌──────────┐   ┌──────────┐   ┌──────────┐
│   Data   │──►│ Features │──►│  Train   │──►│  Model   │
└──────────┘   └──────────┘   └────┬─────┘   └──────────┘
                                   │ metrics
                                   ▼
                              ┌──────────┐
                              │ Evaluate │
                              └──────────┘`,
    nodes: ['data', 'features', 'train', 'model', 'evaluate'],
    edges: [
      ['data', 'features'],
      ['features', 'train'],
      ['train', 'model'],
      ['train', 'evaluate', 'metrics'],
    ],
  },
  {
    name: 'approvalFlow',
    category: 'linear',
    art: `┌─────────┐   ┌──────────┐   ┌──────────┐   ┌───────────┐
│  Draft  │──►│  Review  │──►│ Approved │──►│ Published │
└─────────┘   └──────────┘   └──────────┘   └───────────┘`,
    nodes: ['draft', 'review', 'approved', 'published'],
    edges: [
      ['draft', 'review'],
      ['review', 'approved'],
      ['approved', 'published'],
    ],
  },
  {
    name: 'loadBalancerFanout',
    category: 'fan-out',
    art: `           ┌───────────────┐
           │ Load Balancer │
           └──┬──┬──┬──┬───┘
       ┌──────┘  │  │  └──────┐
       ▼         ▼  ▼         ▼
    ┌──────┐┌──────┐┌──────┐┌──────┐
    │ Web1 ││ Web2 ││ Web3 ││ Web4 │
    └──────┘└──────┘└──────┘└──────┘`,
    nodes: ['load-balancer', 'web1', 'web2', 'web3', 'web4'],
    edges: [
      ['load-balancer', 'web1'],
      ['load-balancer', 'web2'],
      ['load-balancer', 'web3'],
      ['load-balancer', 'web4'],
    ],
  },
  {
    name: 'pubsubBroker',
    category: 'fan-out',
    art: `  ┌──────────┐      ┌──────────┐
  │ Producer │─────►│  Broker  │
  └──────────┘      └─┬──┬──┬──┘
            ┌─────────┘  │  └─────────┐
            ▼            ▼            ▼
      ┌──────────┐┌──────────┐┌──────────┐
      │   Sub1   ││   Sub2   ││   Sub3   │
      └──────────┘└──────────┘└──────────┘`,
    nodes: ['producer', 'broker', 'sub1', 'sub2', 'sub3'],
    edges: [
      ['producer', 'broker'],
      ['broker', 'sub1'],
      ['broker', 'sub2'],
      ['broker', 'sub3'],
    ],
  },
  {
    name: 'collectorFanin',
    category: 'fan-in',
    art: `┌────┐  ┌────┐  ┌────┐
│ S1 │  │ S2 │  │ S3 │
└─┬──┘  └─┬──┘  └─┬──┘
  │       │       │
  ▼       ▼       ▼
┌─────────────────────┐
│      Collector      │
└─────────────────────┘`,
    nodes: ['s1', 's2', 's3', 'collector'],
    edges: [
      ['s1', 'collector'],
      ['s2', 'collector'],
      ['s3', 'collector'],
    ],
  },
  {
    name: 'sharedCache',
    category: 'fan-in',
    art: `┌──────────┐   ┌──────────┐   ┌──────────┐
│ Service1 │   │ Service2 │   │ Service3 │
└────┬─────┘   └────┬─────┘   └────┬─────┘
     │              │              │
     ▼              ▼              ▼
┌────────────────────────────────────────┐
│              Shared Cache              │
└────────────────────────────────────────┘`,
    nodes: ['service1', 'service2', 'service3', 'shared-cache'],
    edges: [
      ['service1', 'shared-cache'],
      ['service2', 'shared-cache'],
      ['service3', 'shared-cache'],
    ],
  },
  {
    name: 'diamond',
    category: 'dag',
    art: `       ┌───┐
       │ A │
       └┬─┬┘
    ┌───┘ └───┐
    ▼         ▼
  ┌───┐     ┌───┐
  │ B │     │ C │
  └─┬─┘     └─┬─┘
    └───┐ ┌───┘
        ▼ ▼
       ┌───┐
       │ D │
       └───┘`,
    nodes: ['a', 'b', 'c', 'd'],
    edges: [
      ['a', 'b'],
      ['a', 'c'],
      ['b', 'd'],
      ['c', 'd'],
    ],
  },
  {
    name: 'orgTree',
    category: 'dag',
    art: `              ┌───────┐
              │  CEO  │
              └───┬───┘
        ┌─────────┴─────────┐
        ▼                   ▼
    ┌───────┐           ┌───────┐
    │ VP-Eng│           │ VP-Ops│
    └───┬───┘           └───────┘
    ┌───┴───┐
    ▼       ▼
┌───────┐┌───────┐
│  Dev  ││  QA   │
└───────┘└───────┘`,
    nodes: ['ceo', 'vp-eng', 'vp-ops', 'dev', 'qa'],
    edges: [
      ['ceo', 'vp-eng'],
      ['ceo', 'vp-ops'],
      ['vp-eng', 'dev'],
      ['vp-eng', 'qa'],
    ],
  },
  {
    name: 'decisionTree',
    category: 'dag',
    art: `        ┌───────────┐
        │  Check?   │
        └──┬─────┬──┘
           │     │
           ▼     ▼
    ┌────────┐ ┌────────┐
    │ Accept │ │ Reject │
    └────────┘ └────────┘`,
    nodes: ['check', 'accept', 'reject'],
    edges: [
      ['check', 'accept'],
      ['check', 'reject'],
    ],
  },
  {
    name: 'microservices',
    category: 'dag',
    art: `              ┌──────────────┐
              │   Gateway    │
              └──┬────┬────┬─┘
      ┌──────────┘    │    └──────────┐
      ▼               ▼               ▼
┌──────────┐    ┌──────────┐    ┌──────────┐
│  Users   │    │  Orders  │    │ Payments │
└────┬─────┘    └────┬─────┘    └────┬─────┘
     ▼               ▼               ▼
┌──────────┐    ┌──────────┐    ┌──────────┐
│ UsersDB  │    │ OrdersDB │    │  PayDB   │
└──────────┘    └──────────┘    └──────────┘`,
    nodes: ['gateway', 'users', 'orders', 'payments', 'usersdb', 'ordersdb', 'paydb'],
    edges: [
      ['gateway', 'users'],
      ['gateway', 'orders'],
      ['gateway', 'payments'],
      ['users', 'usersdb'],
      ['orders', 'ordersdb'],
      ['payments', 'paydb'],
    ],
  },
  {
    name: 'layered',
    category: 'dag',
    art: `┌─────────────────────────────┐
│      Presentation Layer     │
└──────────────┬──────────────┘
               ▼
┌─────────────────────────────┐
│       Business Layer        │
└──────────────┬──────────────┘
               ▼
┌─────────────────────────────┐
│         Data Layer          │
└─────────────────────────────┘`,
    nodes: ['presentation-layer', 'business-layer', 'data-layer'],
    edges: [
      ['presentation-layer', 'business-layer'],
      ['business-layer', 'data-layer'],
    ],
  },
  {
    name: 'threeTier',
    category: 'dag',
    art: `┌──────────┐     ┌──────────┐     ┌──────────┐
│ Browser  │────►│   App    │────►│    DB    │
└──────────┘     └────┬─────┘     └──────────┘
                      │
                      ▼
                 ┌──────────┐
                 │  Cache   │
                 └──────────┘`,
    nodes: ['browser', 'app', 'db', 'cache'],
    edges: [
      ['browser', 'app'],
      ['app', 'db'],
      ['app', 'cache'],
    ],
  },
  {
    name: 'retryLoop',
    category: 'cycle',
    art: `┌─────────┐         ┌──────────┐
│ Request │ ──────> │  Worker  │
└─────────┘         └────┬─────┘
     ▲                   │
     └───────────────────┘`,
    nodes: ['request', 'worker'],
    edges: [
      ['request', 'worker'],
      ['worker', 'request'],
    ],
  },
  {
    name: 'stateMachine',
    category: 'cycle',
    art: `┌─────────┐          ┌─────────┐         ┌──────────┐
│  Idle   │ ───────> │ Running │ ──────> │ Complete │
└─────────┘          └────┬────┘         └──────────┘
     ▲                    │
     └────────────────────┘`,
    nodes: ['idle', 'running', 'complete'],
    edges: [
      ['idle', 'running'],
      ['running', 'complete'],
      ['running', 'idle'],
    ],
  },
  {
    name: 'circuitBreaker',
    category: 'cycle',
    art: `              ┌──────────┐
              │  Closed  │
              └──┬─────┬─┘
                 │     ▲
     ┌───────────┘     │
     ▼                 │
┌──────────┐     ┌─────┴─────┐
│   Open   │────►│ Half-Open │
└──────────┘     └───────────┘`,
    nodes: ['closed', 'open', 'half-open'],
    edges: [
      ['closed', 'open'],
      ['open', 'half-open'],
      ['half-open', 'closed'],
    ],
  },
  {
    name: 'fullMesh3',
    category: 'many-to-many',
    art: `              ┌───────┐
              │ Alpha │
              └──┬─┬──┘
                 ▲ ▲
     ┌───────────┘ │
     │             └────────────┐
     ▼                          ▼
  ┌──────┐                  ┌───────┐
  │ Beta ├◄────────────────►┤ Gamma │
  └──────┘                  └───────┘`,
    nodes: ['alpha', 'beta', 'gamma'],
    edges: [
      ['alpha', 'beta'],
      ['beta', 'alpha'],
      ['alpha', 'gamma'],
      ['gamma', 'alpha'],
      ['beta', 'gamma'],
      ['gamma', 'beta'],
    ],
  },
  {
    name: 'bidirReplication',
    category: 'edges',
    art: `┌──────────┐               ┌──────────┐
│ Primary  │ <───────────> │ Replica  │
└──────────┘               └──────────┘`,
    nodes: ['primary', 'replica'],
    edges: [
      ['primary', 'replica'],
      ['replica', 'primary'],
    ],
  },
  {
    name: 'undirectedPair',
    category: 'edges',
    art: `┌────────┐          ┌────────┐
│ NodeA  │──────────│ NodeB  │
└────────┘          └────────┘`,
    nodes: ['nodea', 'nodeb'],
    edges: [['nodea', 'nodeb', undefined, false]],
  },
  {
    name: 'labeledTyped',
    category: 'labels',
    art: `┌──────────┐              ┌──────────┐
│   API    │ ─── reads ──►│ Database │
└────┬─────┘              └──────────┘
     │ writes
     ▼
┌──────────┐
│  Cache   │
└──────────┘`,
    nodes: ['api', 'database', 'cache'],
    edges: [
      ['api', 'database', 'reads'],
      ['api', 'cache', 'writes'],
    ],
  },
  {
    name: 'queueDlq',
    category: 'labels',
    art: `┌──────────┐     ┌──────────┐     ┌──────────┐
│ Producer │────►│  Queue   │────►│ Consumer │
└──────────┘     └────┬─────┘     └──────────┘
                      │ on-fail
                      ▼
                 ┌──────────┐
                 │   DLQ    │
                 └──────────┘`,
    nodes: ['producer', 'queue', 'consumer', 'dlq'],
    edges: [
      ['producer', 'queue'],
      ['queue', 'consumer'],
      ['queue', 'dlq', 'on-fail'],
    ],
  },
  {
    name: 'cqrs',
    category: 'labels',
    art: `┌──────────┐                    ┌──────────────┐
│  Client  │─── command ───────►│ Write Model  │
└────┬─────┘                    └──────┬───────┘
     │ query                          │ events
     ▼                                ▼
┌──────────────┐                 ┌──────────────┐
│  Read Model  │◄────────────────│ Event Store  │
└──────────────┘                 └──────────────┘`,
    nodes: ['client', 'write-model', 'read-model', 'event-store'],
    edges: [
      ['client', 'write-model', 'command'],
      ['client', 'read-model', 'query'],
      ['write-model', 'event-store', 'events'],
      ['event-store', 'read-model'],
    ],
  },
  {
    name: 'multilineLabels',
    category: 'labels',
    art: `┌──────────────┐        ┌──────────────┐
│ molen-kernel │        │ molen-client │
│ headless sim │───────►│ three.js     │
│ no DOM       │        │ WebGL        │
└──────────────┘        └──────────────┘`,
    nodes: ['molen-kernel', 'molen-client'],
    edges: [['molen-kernel', 'molen-client']],
  },
  {
    name: 'k8sCluster',
    category: 'container',
    art: `┌───────────── Kubernetes Cluster ─────────────┐
│                                              │
│  ┌─────────┐    ┌─────────┐    ┌─────────┐   │
│  │  Pod A  │    │  Pod B  │    │  Pod C  │   │
│  └─────────┘    └─────────┘    └─────────┘   │
│                                              │
└──────────────────────────────────────────────┘`,
    nodes: ['kubernetes-cluster', 'pod-a', 'pod-b', 'pod-c'],
    edges: [],
    containers: {
      'pod-a': 'kubernetes-cluster',
      'pod-b': 'kubernetes-cluster',
      'pod-c': 'kubernetes-cluster',
    },
  },
  {
    name: 'twoRegions',
    category: 'container',
    art: `┌──── Region US ─────┐   ┌──── Region EU ─────┐
│                    │   │                    │
│  ┌──────────────┐  │   │  ┌──────────────┐  │
│  │  us-worker   │  │   │  │  eu-worker   │  │
│  └──────────────┘  │   │  └──────────────┘  │
│                    │   │                    │
└────────────────────┘   └────────────────────┘`,
    nodes: ['region-us', 'us-worker', 'region-eu', 'eu-worker'],
    edges: [],
    containers: { 'us-worker': 'region-us', 'eu-worker': 'region-eu' },
  },
  {
    name: 'nestedTwoLevels',
    category: 'container',
    art: `┌─────────── Region ────────────┐
│                               │
│  ┌─────── Zone A ────────┐    │
│  │                       │    │
│  │  ┌──────────────┐     │    │
│  │  │  Instance 1  │     │    │
│  │  └──────────────┘     │    │
│  │                       │    │
│  └───────────────────────┘    │
│                               │
└───────────────────────────────┘`,
    nodes: ['region', 'zone-a', 'instance-1'],
    edges: [],
    containers: { 'zone-a': 'region', 'instance-1': 'zone-a' },
  },
  {
    name: 'roundedCorners',
    category: 'style',
    art: `╭─────────╮      ╭─────────╮
│  Start  │ ───► │   End   │
╰─────────╯      ╰─────────╯`,
    nodes: ['start', 'end'],
    edges: [['start', 'end']],
  },
];
