/**
 * Battle-test corpus for the ASCII treeview codec: a broad set of AI-style
 * trees (project scaffolds, monorepos, dependency trees, category/decision
 * outlines, forests) with their intended flat semantics. Every fixture is
 * verified to detect + parse to exactly this shape + round-trip byte-stably.
 *
 * GENERATED by scratchpad/gen-tree-fixtures.mjs — edit there and re-run.
 */

export interface TreeFixture {
  name: string;
  category: string;
  art: string;
  /** Flat "depth:label[ #comment]" lines, depth-first. */
  expect: string[];
}

export const TREE_FIXTURES: TreeFixture[] = [
  {
    name: 'reactApp',
    category: 'scaffold',
    art: `my-app/
├── public/
│   └── index.html
├── src/
│   ├── App.tsx
│   ├── index.tsx
│   └── components/
│       ├── Header.tsx
│       └── Footer.tsx
├── package.json
└── tsconfig.json`,
    expect: [
      '0:my-app/',
      '1:public/',
      '2:index.html',
      '1:src/',
      '2:App.tsx',
      '2:index.tsx',
      '2:components/',
      '3:Header.tsx',
      '3:Footer.tsx',
      '1:package.json',
      '1:tsconfig.json',
    ],
  },
  {
    name: 'pythonPkg',
    category: 'scaffold',
    art: `mypackage/
├── __init__.py
├── core.py
├── utils/
│   ├── __init__.py
│   └── helpers.py
└── tests/
    └── test_core.py`,
    expect: [
      '0:mypackage/',
      '1:__init__.py',
      '1:core.py',
      '1:utils/',
      '2:__init__.py',
      '2:helpers.py',
      '1:tests/',
      '2:test_core.py',
    ],
  },
  {
    name: 'monorepo',
    category: 'scaffold',
    art: `workspace/
├── packages/
│   ├── core/
│   ├── ui/
│   └── cli/
├── apps/
│   └── web/
└── package.json`,
    expect: [
      '0:workspace/',
      '1:packages/',
      '2:core/',
      '2:ui/',
      '2:cli/',
      '1:apps/',
      '2:web/',
      '1:package.json',
    ],
  },
  {
    name: 'asciiStyle',
    category: 'style',
    art: `docs/
|-- guide.md
|-- api/
|   |-- rest.md
|   \`-- graphql.md
\`-- README.md`,
    expect: ['0:docs/', '1:guide.md', '1:api/', '2:rest.md', '2:graphql.md', '1:README.md'],
  },
  {
    name: 'plusStyle',
    category: 'style',
    art: `root
+-- moduleA
|   +-- fileA1
|   +-- fileA2
+-- moduleB
    +-- fileB1`,
    expect: ['0:root', '1:moduleA', '2:fileA1', '2:fileA2', '1:moduleB', '2:fileB1'],
  },
  {
    name: 'withComments',
    category: 'comments',
    art: `service/
├── main.go       # entrypoint
├── config.yaml   # runtime config
├── handlers/     # HTTP handlers
│   └── users.go
└── go.mod`,
    expect: [
      '0:service/',
      '1:main.go #entrypoint',
      '1:config.yaml #runtime config',
      '1:handlers/ #HTTP handlers',
      '2:users.go',
      '1:go.mod',
    ],
  },
  {
    name: 'depTree',
    category: 'outline',
    art: `express@4.18.2
├── body-parser@1.20.1
│   ├── bytes@3.1.2
│   └── qs@6.11.0
├── cookie@0.5.0
└── debug@2.6.9
    └── ms@2.0.0`,
    expect: [
      '0:express@4.18.2',
      '1:body-parser@1.20.1',
      '2:bytes@3.1.2',
      '2:qs@6.11.0',
      '1:cookie@0.5.0',
      '1:debug@2.6.9',
      '2:ms@2.0.0',
    ],
  },
  {
    name: 'categoryOutline',
    category: 'outline',
    art: `Animals
├── Mammals
│   ├── Dogs
│   └── Cats
├── Birds
│   ├── Eagles
│   └── Sparrows
└── Reptiles
    └── Snakes`,
    expect: [
      '0:Animals',
      '1:Mammals',
      '2:Dogs',
      '2:Cats',
      '1:Birds',
      '2:Eagles',
      '2:Sparrows',
      '1:Reptiles',
      '2:Snakes',
    ],
  },
  {
    name: 'decisionOutline',
    category: 'outline',
    art: `Deploy?
├── Tests pass
│   ├── Deploy to staging
│   └── Run smoke tests
└── Tests fail
    └── Notify team`,
    expect: [
      '0:Deploy?',
      '1:Tests pass',
      '2:Deploy to staging',
      '2:Run smoke tests',
      '1:Tests fail',
      '2:Notify team',
    ],
  },
  {
    name: 'forest',
    category: 'shape',
    art: `frontend/
├── index.html
└── app.js
backend/
├── server.py
└── models.py
shared/
└── types.ts`,
    expect: [
      '0:frontend/',
      '1:index.html',
      '1:app.js',
      '0:backend/',
      '1:server.py',
      '1:models.py',
      '0:shared/',
      '1:types.ts',
    ],
  },
  {
    name: 'deepChain',
    category: 'shape',
    art: `a/
└── b/
    └── c/
        └── d/
            └── e.txt`,
    expect: ['0:a/', '1:b/', '2:c/', '3:d/', '4:e.txt'],
  },
  {
    name: 'wideFlat',
    category: 'shape',
    art: `config/
├── dev.json
├── staging.json
├── prod.json
├── test.json
└── local.json`,
    expect: [
      '0:config/',
      '1:dev.json',
      '1:staging.json',
      '1:prod.json',
      '1:test.json',
      '1:local.json',
    ],
  },
];
