/**
 * CaptionOverlay Component
 *
 * Displays closed captions synchronized with audio playback.
 * Captions cross-fade smoothly using CSS transitions on a single
 * persistent element (no mount/unmount flicker).
 *
 * The captions are generated by the postprocess-doc command based
 * on article text and audio segment timing.
 */

import type { CaptionTrack } from '@bendyline/prodcore/schemas';
import { getCaptionAtTime } from '@bendyline/prodcore/schemas';

interface CaptionOverlayProps {
  /** Caption track with timestamped phrases */
  captions: CaptionTrack | undefined;
  /** Current playback time in seconds */
  currentTime: number;
  /** Whether captions are enabled */
  enabled?: boolean;
  /** Font size in pixels (default: 16) */
  fontSize?: number;
}

export function CaptionOverlay({
  captions,
  currentTime,
  enabled = true,
  fontSize = 16,
}: CaptionOverlayProps) {
  // Derive caption directly from currentTime -- pure computation, no hooks.
  // This avoids race conditions between timeupdate events and async state updates.
  const phrase = (enabled && captions) ? getCaptionAtTime(captions, currentTime) : null;
  const captionText = phrase?.text ?? null;

  return (
    <div
      className="caption-overlay"
      style={{
        position: 'absolute',
        top: '6px',
        left: '50%',
        transform: 'translateX(-50%)',
        zIndex: 50,
        pointerEvents: 'none',
        maxWidth: '100%',
        width: '100%',
        textAlign: 'center',
        opacity: captionText ? 1 : 0,
        transition: 'opacity 0.15s ease-in-out',
        padding: '0 4px',
        boxSizing: 'border-box',
      }}
    >
      {captionText && (
        <div
          style={{
            display: 'inline-block',
            padding: '3px 10px',
            background: 'rgba(0, 0, 0, 0.65)',
            borderRadius: '4px',
            backdropFilter: 'blur(4px)',
          }}
        >
          <span
            style={{
              color: '#ffffff',
              fontSize: `${fontSize}px`,
              fontFamily: "'Hanken Grotesk', system-ui, sans-serif",
              fontWeight: 500,
              lineHeight: 1.25,
              textShadow: '0 1px 3px rgba(0,0,0,0.5)',
              whiteSpace: 'pre-wrap',
              wordWrap: 'break-word',
            }}
          >
            {captionText}
          </span>
        </div>
      )}
    </div>
  );
}

export default CaptionOverlay;