/**
 * Type declaration for the `@bendyline/squisq-react/standalone-source`
 * subpath export. The runtime JS file is generated by
 * `scripts/generate-standalone-source.mjs` after the IIFE build emits
 * `dist/squisq-player.global.js`, but the type surface is constant —
 * it always exposes the same single `string` constant — so the
 * declaration lives in source so consumers can typecheck without
 * having had to build this package first.
 */
export declare const PLAYER_BUNDLE: string;
