/**
 * Emoji Dataset
 *
 * Curated set of common emoji grouped by Unicode CLDR category. Used by
 * `EmojiPicker` for both the category tabs and the search index.
 *
 * Each entry is a flat tuple `[char, name, ...keywords]` so the data
 * stays compact in source and is cheap to scan for the typeahead
 * search. Categories follow the official Unicode buckets in display
 * order (CLDR v44 grouping), trimmed to common picks per category —
 * we deliberately don't ship the whole Unicode emoji set (thousands)
 * because the picker is meant for quick insertion, not exhaustive
 * lookup; the user can paste anything we don't have.
 */

export interface EmojiEntry {
  /** The actual emoji glyph (may be multi-codepoint, e.g. ZWJ sequences). */
  char: string;
  /** Display name shown in the tooltip. */
  name: string;
  /** Lowercase keywords for the search index — name words plus aliases. */
  keywords: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  /** Single-glyph icon shown on the tab. */
  icon: string;
  emojis: EmojiEntry[];
}

function e(char: string, name: string, ...kw: string[]): EmojiEntry {
  return { char, name, keywords: [name, ...kw].join(' ').toLowerCase() };
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys',
    icon: '😀',
    emojis: [
      e('😀', 'grinning'),
      e('😃', 'smiley'),
      e('😄', 'smile', 'happy'),
      e('😁', 'grin', 'beaming'),
      e('😆', 'laughing'),
      e('😅', 'sweat smile'),
      e('🤣', 'rofl', 'rolling laughing'),
      e('😂', 'joy', 'laughing tears'),
      e('🙂', 'slight smile'),
      e('🙃', 'upside down'),
      e('😉', 'wink'),
      e('😊', 'blush'),
      e('😇', 'innocent', 'halo'),
      e('🥰', 'smiling hearts'),
      e('😍', 'heart eyes'),
      e('🤩', 'star struck'),
      e('😘', 'kiss', 'blow kiss'),
      e('😗', 'kissing'),
      e('😚', 'kissing closed eyes'),
      e('😙', 'kissing smile'),
      e('🥲', 'smiling tear'),
      e('😋', 'yum', 'tongue'),
      e('😛', 'tongue out'),
      e('😜', 'wink tongue'),
      e('🤪', 'zany', 'crazy'),
      e('😝', 'squint tongue'),
      e('🤑', 'money face'),
      e('🤗', 'hugging'),
      e('🤭', 'hand over mouth'),
      e('🤫', 'shushing'),
      e('🤔', 'thinking'),
      e('🤐', 'zipper mouth'),
      e('🤨', 'raised eyebrow'),
      e('😐', 'neutral'),
      e('😑', 'expressionless'),
      e('😶', 'no mouth'),
      e('😏', 'smirk'),
      e('😒', 'unamused'),
      e('🙄', 'eye roll'),
      e('😬', 'grimace'),
      e('🤥', 'lying', 'pinocchio'),
      e('😌', 'relieved'),
      e('😔', 'pensive'),
      e('😪', 'sleepy'),
      e('🤤', 'drool'),
      e('😴', 'sleeping', 'zzz'),
      e('😷', 'mask'),
      e('🤒', 'thermometer face'),
      e('🤕', 'head bandage'),
      e('🤢', 'nauseated'),
      e('🤮', 'vomiting'),
      e('🤧', 'sneeze'),
      e('🥵', 'hot face'),
      e('🥶', 'cold face'),
      e('🥴', 'woozy'),
      e('😵', 'dizzy'),
      e('🤯', 'mind blown', 'exploding head'),
      e('🤠', 'cowboy'),
      e('🥳', 'partying'),
      e('🥸', 'disguised'),
      e('😎', 'sunglasses', 'cool'),
      e('🤓', 'nerd', 'glasses'),
      e('🧐', 'monocle'),
      e('😕', 'confused'),
      e('😟', 'worried'),
      e('🙁', 'slight frown'),
      e('☹️', 'frown'),
      e('😮', 'open mouth'),
      e('😯', 'hushed'),
      e('😲', 'astonished'),
      e('😳', 'flushed'),
      e('🥺', 'pleading'),
      e('😦', 'frowning open mouth'),
      e('😧', 'anguished'),
      e('😨', 'fearful'),
      e('😰', 'anxious sweat'),
      e('😥', 'sad relieved'),
      e('😢', 'cry'),
      e('😭', 'sobbing', 'loud cry'),
      e('😱', 'screaming', 'shocked'),
      e('😖', 'confounded'),
      e('😣', 'persevering'),
      e('😞', 'disappointed'),
      e('😓', 'downcast sweat'),
      e('😩', 'weary'),
      e('😫', 'tired'),
      e('😤', 'triumph'),
      e('😡', 'pout', 'red angry'),
      e('😠', 'angry'),
      e('🤬', 'cursing', 'symbols'),
      e('😈', 'smiling devil'),
      e('👿', 'angry devil'),
      e('💀', 'skull'),
      e('💩', 'poop', 'pile'),
      e('🤡', 'clown'),
      e('👻', 'ghost'),
      e('👽', 'alien'),
      e('🤖', 'robot'),
      e('🎃', 'jack o lantern', 'pumpkin'),
    ],
  },
  {
    id: 'people',
    label: 'People',
    icon: '👋',
    emojis: [
      e('👋', 'wave', 'hello'),
      e('🤚', 'raised back hand'),
      e('🖐️', 'raised hand fingers'),
      e('✋', 'raised hand', 'stop'),
      e('🖖', 'vulcan'),
      e('👌', 'ok hand'),
      e('🤌', 'pinched fingers'),
      e('🤏', 'pinching'),
      e('✌️', 'peace'),
      e('🤞', 'crossed fingers', 'luck'),
      e('🤟', 'love you gesture'),
      e('🤘', 'rock on', 'horns'),
      e('🤙', 'call me'),
      e('👈', 'point left'),
      e('👉', 'point right'),
      e('👆', 'point up'),
      e('👇', 'point down'),
      e('☝️', 'index up'),
      e('👍', 'thumbs up', 'like'),
      e('👎', 'thumbs down', 'dislike'),
      e('✊', 'raised fist'),
      e('👊', 'oncoming fist', 'punch'),
      e('🤛', 'left fist', 'bump'),
      e('🤜', 'right fist'),
      e('👏', 'clap'),
      e('🙌', 'raised hands', 'praise'),
      e('👐', 'open hands'),
      e('🤲', 'palms up'),
      e('🤝', 'handshake'),
      e('🙏', 'pray', 'thanks'),
      e('💪', 'muscle', 'strong'),
      e('🦵', 'leg'),
      e('🦶', 'foot'),
      e('👂', 'ear'),
      e('🦻', 'ear hearing aid'),
      e('👃', 'nose'),
      e('🧠', 'brain'),
      e('🫀', 'heart anatomy'),
      e('🫁', 'lungs'),
      e('🦷', 'tooth'),
      e('🦴', 'bone'),
      e('👀', 'eyes'),
      e('👁️', 'eye'),
      e('👅', 'tongue'),
      e('👄', 'mouth'),
      e('💋', 'lipstick kiss'),
      e('👶', 'baby'),
      e('🧒', 'child'),
      e('👦', 'boy'),
      e('👧', 'girl'),
      e('🧑', 'person'),
      e('👨', 'man'),
      e('👩', 'woman'),
      e('🧓', 'older person'),
      e('👴', 'old man'),
      e('👵', 'old woman'),
      e('👮', 'police'),
      e('🕵️', 'detective'),
      e('💂', 'guard'),
      e('🧑‍⚕️', 'health worker'),
      e('🧑‍🎓', 'student'),
      e('🧑‍🏫', 'teacher'),
      e('🧑‍🔧', 'mechanic'),
      e('🧑‍💻', 'technologist', 'developer'),
      e('🧑‍🎨', 'artist'),
      e('🧑‍🚀', 'astronaut'),
      e('🧑‍🚒', 'firefighter'),
      e('👷', 'construction worker'),
      e('🤴', 'prince'),
      e('👸', 'princess'),
      e('🦸', 'superhero'),
      e('🦹', 'supervillain'),
      e('🧙', 'mage', 'wizard'),
      e('🧚', 'fairy'),
      e('🧛', 'vampire'),
      e('🧜', 'merperson'),
      e('🧝', 'elf'),
      e('🧞', 'genie'),
      e('🧟', 'zombie'),
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icon: '🌿',
    emojis: [
      e('🐶', 'dog face'),
      e('🐱', 'cat face'),
      e('🐭', 'mouse'),
      e('🐹', 'hamster'),
      e('🐰', 'rabbit face'),
      e('🦊', 'fox'),
      e('🐻', 'bear'),
      e('🐼', 'panda'),
      e('🐻‍❄️', 'polar bear'),
      e('🐨', 'koala'),
      e('🐯', 'tiger face'),
      e('🦁', 'lion'),
      e('🐮', 'cow face'),
      e('🐷', 'pig face'),
      e('🐽', 'pig nose'),
      e('🐸', 'frog'),
      e('🐵', 'monkey face'),
      e('🙈', 'see no evil'),
      e('🙉', 'hear no evil'),
      e('🙊', 'speak no evil'),
      e('🐒', 'monkey'),
      e('🐔', 'chicken'),
      e('🐧', 'penguin'),
      e('🐦', 'bird'),
      e('🐤', 'baby chick'),
      e('🐣', 'hatching chick'),
      e('🦆', 'duck'),
      e('🦅', 'eagle'),
      e('🦉', 'owl'),
      e('🦇', 'bat'),
      e('🐺', 'wolf'),
      e('🐗', 'boar'),
      e('🐴', 'horse face'),
      e('🦄', 'unicorn'),
      e('🐝', 'bee'),
      e('🐛', 'bug'),
      e('🦋', 'butterfly'),
      e('🐌', 'snail'),
      e('🐞', 'lady beetle'),
      e('🐜', 'ant'),
      e('🦂', 'scorpion'),
      e('🕷️', 'spider'),
      e('🐢', 'turtle'),
      e('🐍', 'snake'),
      e('🦖', 'trex'),
      e('🦕', 'sauropod'),
      e('🐙', 'octopus'),
      e('🦑', 'squid'),
      e('🦐', 'shrimp'),
      e('🦞', 'lobster'),
      e('🦀', 'crab'),
      e('🐡', 'blowfish'),
      e('🐠', 'tropical fish'),
      e('🐟', 'fish'),
      e('🐬', 'dolphin'),
      e('🐳', 'spouting whale'),
      e('🐋', 'whale'),
      e('🦈', 'shark'),
      e('🐊', 'crocodile'),
      e('🐅', 'tiger'),
      e('🐆', 'leopard'),
      e('🦓', 'zebra'),
      e('🦍', 'gorilla'),
      e('🦧', 'orangutan'),
      e('🐘', 'elephant'),
      e('🦛', 'hippopotamus'),
      e('🦏', 'rhinoceros'),
      e('🐪', 'camel'),
      e('🐫', 'two hump camel'),
      e('🦒', 'giraffe'),
      e('🦘', 'kangaroo'),
      e('🐃', 'water buffalo'),
      e('🐂', 'ox'),
      e('🐄', 'cow'),
      e('🐎', 'horse'),
      e('🐖', 'pig'),
      e('🐏', 'ram'),
      e('🐑', 'ewe'),
      e('🦙', 'llama'),
      e('🐐', 'goat'),
      e('🦌', 'deer'),
      e('🐕', 'dog'),
      e('🐩', 'poodle'),
      e('🦮', 'guide dog'),
      e('🐕‍🦺', 'service dog'),
      e('🐈', 'cat'),
      e('🐈‍⬛', 'black cat'),
      e('🐓', 'rooster'),
      e('🦃', 'turkey'),
      e('🦚', 'peacock'),
      e('🦜', 'parrot'),
      e('🦢', 'swan'),
      e('🌲', 'evergreen tree'),
      e('🌳', 'deciduous tree'),
      e('🌴', 'palm tree'),
      e('🌵', 'cactus'),
      e('🌷', 'tulip'),
      e('🌸', 'cherry blossom'),
      e('🌹', 'rose'),
      e('🥀', 'wilted flower'),
      e('🌺', 'hibiscus'),
      e('🌻', 'sunflower'),
      e('🌼', 'blossom'),
      e('🌱', 'seedling'),
      e('🪴', 'potted plant'),
      e('🌿', 'herb'),
      e('☘️', 'shamrock'),
      e('🍀', 'four leaf clover'),
      e('🍁', 'maple leaf'),
      e('🍂', 'fallen leaf'),
      e('🍃', 'leaf wind'),
      e('🌞', 'sun face'),
      e('☀️', 'sun'),
      e('🌝', 'full moon face'),
      e('🌚', 'new moon face'),
      e('🌛', 'first quarter moon face'),
      e('🌜', 'last quarter moon face'),
      e('🌙', 'crescent moon'),
      e('🌎', 'earth americas'),
      e('🌍', 'earth europe africa'),
      e('🌏', 'earth asia australia'),
      e('🪐', 'ringed planet'),
      e('⭐', 'star'),
      e('🌟', 'glowing star'),
      e('✨', 'sparkles'),
      e('⚡', 'lightning', 'bolt'),
      e('☄️', 'comet'),
      e('🔥', 'fire'),
      e('💥', 'collision', 'boom'),
      e('🌈', 'rainbow'),
      e('☁️', 'cloud'),
      e('⛅', 'sun behind cloud'),
      e('🌧️', 'rain cloud'),
      e('⛈️', 'thunder cloud'),
      e('🌩️', 'lightning cloud'),
      e('🌨️', 'snow cloud'),
      e('❄️', 'snowflake'),
      e('⛄', 'snowman'),
      e('🌪️', 'tornado'),
      e('🌫️', 'fog'),
      e('🌊', 'wave'),
      e('💧', 'droplet'),
      e('💦', 'sweat drops'),
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍎',
    emojis: [
      e('🍏', 'green apple'),
      e('🍎', 'red apple'),
      e('🍐', 'pear'),
      e('🍊', 'tangerine', 'orange'),
      e('🍋', 'lemon'),
      e('🍌', 'banana'),
      e('🍉', 'watermelon'),
      e('🍇', 'grapes'),
      e('🍓', 'strawberry'),
      e('🫐', 'blueberries'),
      e('🍈', 'melon'),
      e('🍒', 'cherries'),
      e('🍑', 'peach'),
      e('🥭', 'mango'),
      e('🍍', 'pineapple'),
      e('🥥', 'coconut'),
      e('🥝', 'kiwi'),
      e('🍅', 'tomato'),
      e('🍆', 'eggplant'),
      e('🥑', 'avocado'),
      e('🥦', 'broccoli'),
      e('🥬', 'leafy green'),
      e('🥒', 'cucumber'),
      e('🌶️', 'pepper'),
      e('🫑', 'bell pepper'),
      e('🌽', 'corn'),
      e('🥕', 'carrot'),
      e('🫒', 'olive'),
      e('🧄', 'garlic'),
      e('🧅', 'onion'),
      e('🥔', 'potato'),
      e('🍠', 'sweet potato'),
      e('🥐', 'croissant'),
      e('🥯', 'bagel'),
      e('🍞', 'bread'),
      e('🥖', 'baguette'),
      e('🥨', 'pretzel'),
      e('🧀', 'cheese'),
      e('🥚', 'egg'),
      e('🍳', 'cooking', 'frying'),
      e('🧈', 'butter'),
      e('🥞', 'pancakes'),
      e('🧇', 'waffle'),
      e('🥓', 'bacon'),
      e('🥩', 'cut of meat'),
      e('🍗', 'poultry leg'),
      e('🍖', 'meat on bone'),
      e('🌭', 'hot dog'),
      e('🍔', 'hamburger'),
      e('🍟', 'fries'),
      e('🍕', 'pizza'),
      e('🥪', 'sandwich'),
      e('🌮', 'taco'),
      e('🌯', 'burrito'),
      e('🥙', 'stuffed flatbread'),
      e('🧆', 'falafel'),
      e('🥗', 'salad'),
      e('🥘', 'shallow pan of food'),
      e('🍝', 'spaghetti'),
      e('🍜', 'steaming bowl'),
      e('🍲', 'pot of food'),
      e('🍛', 'curry'),
      e('🍣', 'sushi'),
      e('🍱', 'bento'),
      e('🥟', 'dumpling'),
      e('🍤', 'shrimp tempura'),
      e('🍙', 'rice ball'),
      e('🍚', 'rice'),
      e('🍘', 'rice cracker'),
      e('🥠', 'fortune cookie'),
      e('🥮', 'moon cake'),
      e('🍢', 'oden'),
      e('🍡', 'dango'),
      e('🦪', 'oyster'),
      e('🍦', 'soft serve'),
      e('🍧', 'shaved ice'),
      e('🍨', 'ice cream'),
      e('🍩', 'doughnut'),
      e('🍪', 'cookie'),
      e('🎂', 'birthday cake'),
      e('🍰', 'shortcake'),
      e('🧁', 'cupcake'),
      e('🥧', 'pie'),
      e('🍫', 'chocolate bar'),
      e('🍬', 'candy'),
      e('🍭', 'lollipop'),
      e('🍮', 'custard'),
      e('🍯', 'honey'),
      e('🍼', 'baby bottle'),
      e('🥛', 'milk'),
      e('☕', 'coffee'),
      e('🫖', 'teapot'),
      e('🍵', 'tea'),
      e('🍶', 'sake'),
      e('🍾', 'champagne'),
      e('🍷', 'wine glass'),
      e('🍸', 'cocktail'),
      e('🍹', 'tropical drink'),
      e('🍺', 'beer'),
      e('🍻', 'clink beers'),
      e('🥂', 'clink champagne'),
      e('🥃', 'tumbler'),
      e('🥤', 'cup straw'),
      e('🧋', 'bubble tea'),
      e('🧃', 'juice box'),
      e('🧉', 'mate'),
      e('🧊', 'ice cube'),
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    icon: '✈️',
    emojis: [
      e('🚗', 'car'),
      e('🚕', 'taxi'),
      e('🚙', 'suv'),
      e('🚌', 'bus'),
      e('🚎', 'trolleybus'),
      e('🏎️', 'racing car'),
      e('🚓', 'police car'),
      e('🚑', 'ambulance'),
      e('🚒', 'fire engine'),
      e('🚐', 'minibus'),
      e('🛻', 'pickup truck'),
      e('🚚', 'delivery truck'),
      e('🚛', 'semi truck'),
      e('🚜', 'tractor'),
      e('🛵', 'motor scooter'),
      e('🏍️', 'motorcycle'),
      e('🚲', 'bicycle'),
      e('🛴', 'kick scooter'),
      e('🛹', 'skateboard'),
      e('🛼', 'roller skate'),
      e('🚂', 'locomotive'),
      e('🚃', 'railway car'),
      e('🚄', 'high speed train'),
      e('🚅', 'bullet train'),
      e('🚆', 'train'),
      e('🚇', 'metro'),
      e('🚈', 'light rail'),
      e('🚉', 'station'),
      e('🚝', 'monorail'),
      e('🚞', 'mountain railway'),
      e('🚋', 'tram'),
      e('🚊', 'tram car'),
      e('🚟', 'suspension railway'),
      e('🚠', 'mountain cableway'),
      e('🚡', 'aerial tramway'),
      e('✈️', 'airplane'),
      e('🛫', 'departing'),
      e('🛬', 'arriving'),
      e('🛩️', 'small airplane'),
      e('🚁', 'helicopter'),
      e('🛸', 'flying saucer'),
      e('🚀', 'rocket'),
      e('🛰️', 'satellite'),
      e('🛶', 'canoe'),
      e('⛵', 'sailboat'),
      e('🚤', 'speedboat'),
      e('🛥️', 'motor boat'),
      e('🛳️', 'passenger ship'),
      e('⛴️', 'ferry'),
      e('🚢', 'ship'),
      e('⚓', 'anchor'),
      e('🪝', 'hook'),
      e('⛽', 'fuel pump'),
      e('🚧', 'construction'),
      e('🚦', 'traffic light'),
      e('🚥', 'horizontal traffic light'),
      e('🗺️', 'map'),
      e('🗿', 'moai'),
      e('🗽', 'statue of liberty'),
      e('🗼', 'tokyo tower'),
      e('🏰', 'castle'),
      e('🏯', 'japanese castle'),
      e('🏟️', 'stadium'),
      e('🎡', 'ferris wheel'),
      e('🎢', 'roller coaster'),
      e('🎠', 'carousel'),
      e('⛲', 'fountain'),
      e('⛱️', 'umbrella ground'),
      e('🏖️', 'beach umbrella'),
      e('🏝️', 'desert island'),
      e('🏜️', 'desert'),
      e('🌋', 'volcano'),
      e('⛰️', 'mountain'),
      e('🏔️', 'snow mountain'),
      e('🗻', 'mount fuji'),
      e('🏕️', 'camping'),
      e('⛺', 'tent'),
      e('🛖', 'hut'),
      e('🏠', 'house'),
      e('🏡', 'house with garden'),
      e('🏘️', 'houses'),
      e('🏚️', 'derelict house'),
      e('🏗️', 'construction site'),
      e('🏭', 'factory'),
      e('🏢', 'office building'),
      e('🏬', 'department store'),
      e('🏣', 'japanese post office'),
      e('🏤', 'post office'),
      e('🏥', 'hospital'),
      e('🏦', 'bank'),
      e('🏨', 'hotel'),
      e('🏪', 'convenience store'),
      e('🏫', 'school'),
      e('🏩', 'love hotel'),
      e('💒', 'wedding'),
      e('🏛️', 'classical building'),
      e('⛪', 'church'),
      e('🕌', 'mosque'),
      e('🛕', 'hindu temple'),
      e('🕍', 'synagogue'),
      e('⛩️', 'shrine'),
      e('🌁', 'foggy city'),
      e('🌃', 'night stars'),
      e('🌄', 'sunrise mountains'),
      e('🌅', 'sunrise'),
      e('🌆', 'cityscape dusk'),
      e('🌇', 'sunset'),
      e('🌉', 'bridge night'),
      e('♨️', 'hot springs'),
      e('🎑', 'moon viewing'),
      e('🏞️', 'national park'),
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      e('⚽', 'soccer'),
      e('🏀', 'basketball'),
      e('🏈', 'football'),
      e('⚾', 'baseball'),
      e('🥎', 'softball'),
      e('🎾', 'tennis'),
      e('🏐', 'volleyball'),
      e('🏉', 'rugby'),
      e('🥏', 'flying disc', 'frisbee'),
      e('🎱', 'pool', 'eight ball'),
      e('🪀', 'yoyo'),
      e('🏓', 'ping pong'),
      e('🏸', 'badminton'),
      e('🏒', 'ice hockey'),
      e('🏑', 'field hockey'),
      e('🥍', 'lacrosse'),
      e('🏏', 'cricket'),
      e('🪃', 'boomerang'),
      e('🥅', 'goal net'),
      e('⛳', 'flag in hole', 'golf'),
      e('🪁', 'kite'),
      e('🏹', 'bow and arrow'),
      e('🎣', 'fishing'),
      e('🤿', 'diving mask'),
      e('🥊', 'boxing glove'),
      e('🥋', 'martial arts'),
      e('🎽', 'running shirt'),
      e('🛹', 'skateboard'),
      e('🛼', 'roller skate'),
      e('🛷', 'sled'),
      e('⛸️', 'ice skate'),
      e('🥌', 'curling stone'),
      e('🎿', 'skis'),
      e('⛷️', 'skier'),
      e('🏂', 'snowboarder'),
      e('🪂', 'parachute'),
      e('🏋️', 'weight lifting'),
      e('🤼', 'wrestling'),
      e('🤸', 'cartwheel'),
      e('⛹️', 'bouncing ball'),
      e('🤺', 'fencing'),
      e('🤾', 'handball'),
      e('🏌️', 'golfing'),
      e('🏇', 'horse racing'),
      e('🧘', 'meditation', 'yoga'),
      e('🏄', 'surfing'),
      e('🏊', 'swimming'),
      e('🤽', 'water polo'),
      e('🚣', 'rowing'),
      e('🧗', 'climbing'),
      e('🚵', 'mountain biker'),
      e('🚴', 'biker'),
      e('🏆', 'trophy'),
      e('🥇', 'gold medal'),
      e('🥈', 'silver medal'),
      e('🥉', 'bronze medal'),
      e('🏅', 'sports medal'),
      e('🎖️', 'military medal'),
      e('🏵️', 'rosette'),
      e('🎗️', 'reminder ribbon'),
      e('🎫', 'ticket'),
      e('🎟️', 'admission tickets'),
      e('🎪', 'circus tent'),
      e('🎭', 'theatre masks'),
      e('🎨', 'art palette'),
      e('🎬', 'clapper board'),
      e('🎤', 'microphone'),
      e('🎧', 'headphone'),
      e('🎼', 'musical score'),
      e('🎹', 'piano'),
      e('🥁', 'drum'),
      e('🪘', 'long drum'),
      e('🎷', 'saxophone'),
      e('🎺', 'trumpet'),
      e('🎸', 'guitar'),
      e('🪕', 'banjo'),
      e('🎻', 'violin'),
      e('🪗', 'accordion'),
      e('🎲', 'game die'),
      e('♟️', 'chess pawn'),
      e('🎯', 'bullseye', 'dart'),
      e('🎳', 'bowling'),
      e('🎮', 'video game'),
      e('🎰', 'slot machine'),
      e('🧩', 'jigsaw'),
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      e('💡', 'light bulb', 'idea'),
      e('🔦', 'flashlight'),
      e('🕯️', 'candle'),
      e('🪔', 'diya lamp'),
      e('🧯', 'fire extinguisher'),
      e('🛢️', 'oil drum'),
      e('💸', 'money wings'),
      e('💵', 'dollar'),
      e('💴', 'yen banknote'),
      e('💶', 'euro banknote'),
      e('💷', 'pound banknote'),
      e('💰', 'money bag'),
      e('💳', 'credit card'),
      e('💎', 'gem'),
      e('⚖️', 'balance scale'),
      e('🪜', 'ladder'),
      e('🧰', 'toolbox'),
      e('🔧', 'wrench'),
      e('🪛', 'screwdriver'),
      e('🔨', 'hammer'),
      e('⚒️', 'hammer and pick'),
      e('🛠️', 'hammer and wrench'),
      e('⛏️', 'pick'),
      e('🪚', 'saw'),
      e('🔩', 'nut and bolt'),
      e('⚙️', 'gear'),
      e('🧱', 'brick'),
      e('⛓️', 'chains'),
      e('🧲', 'magnet'),
      e('🔫', 'water pistol'),
      e('💣', 'bomb'),
      e('🧨', 'firecracker'),
      e('🪓', 'axe'),
      e('🔪', 'kitchen knife'),
      e('🗡️', 'dagger'),
      e('⚔️', 'crossed swords'),
      e('🛡️', 'shield'),
      e('🚬', 'cigarette'),
      e('⚰️', 'coffin'),
      e('🪦', 'headstone'),
      e('⚱️', 'urn'),
      e('🏺', 'amphora'),
      e('🔮', 'crystal ball'),
      e('📿', 'prayer beads'),
      e('🧿', 'nazar amulet'),
      e('💈', 'barber pole'),
      e('⚗️', 'alembic'),
      e('🔭', 'telescope'),
      e('🔬', 'microscope'),
      e('🕳️', 'hole'),
      e('🩹', 'bandage'),
      e('🩺', 'stethoscope'),
      e('💊', 'pill'),
      e('💉', 'syringe'),
      e('🩸', 'blood drop'),
      e('🧬', 'dna'),
      e('🦠', 'microbe'),
      e('🧫', 'petri dish'),
      e('🧪', 'test tube'),
      e('🌡️', 'thermometer'),
      e('🧹', 'broom'),
      e('🪠', 'plunger'),
      e('🧺', 'basket'),
      e('🧻', 'roll of paper'),
      e('🚽', 'toilet'),
      e('🚰', 'tap water'),
      e('🚿', 'shower'),
      e('🛁', 'bathtub'),
      e('🛀', 'person bathing'),
      e('🧼', 'soap'),
      e('🪥', 'toothbrush'),
      e('🪒', 'razor'),
      e('🧽', 'sponge'),
      e('🪣', 'bucket'),
      e('🧴', 'lotion'),
      e('🛎️', 'bellhop bell'),
      e('🔑', 'key'),
      e('🗝️', 'old key'),
      e('🚪', 'door'),
      e('🪑', 'chair'),
      e('🛋️', 'couch'),
      e('🛏️', 'bed'),
      e('🛌', 'person in bed'),
      e('🧸', 'teddy bear'),
      e('🖼️', 'framed picture'),
      e('🪞', 'mirror'),
      e('🪟', 'window'),
      e('🛍️', 'shopping bags'),
      e('🛒', 'cart'),
      e('🎁', 'gift'),
      e('🎀', 'ribbon'),
      e('🎊', 'confetti ball'),
      e('🎉', 'party popper', 'celebration'),
      e('🎈', 'balloon'),
      e('🪄', 'magic wand'),
      e('📱', 'mobile'),
      e('📲', 'incoming phone'),
      e('☎️', 'phone'),
      e('📞', 'phone receiver'),
      e('📟', 'pager'),
      e('📠', 'fax'),
      e('🔋', 'battery'),
      e('🔌', 'plug'),
      e('💻', 'laptop'),
      e('🖥️', 'desktop'),
      e('🖨️', 'printer'),
      e('⌨️', 'keyboard'),
      e('🖱️', 'mouse'),
      e('🖲️', 'trackball'),
      e('💽', 'minidisc'),
      e('💾', 'floppy', 'save'),
      e('💿', 'cd'),
      e('📀', 'dvd'),
      e('🧮', 'abacus'),
      e('🎥', 'movie camera'),
      e('🎞️', 'film frames'),
      e('📽️', 'film projector'),
      e('📺', 'television'),
      e('📷', 'camera'),
      e('📸', 'camera flash'),
      e('📹', 'video camera'),
      e('📼', 'videocassette'),
      e('🔍', 'magnifying left'),
      e('🔎', 'magnifying right'),
      e('🕰️', 'mantelpiece clock'),
      e('⏰', 'alarm clock'),
      e('⏱️', 'stopwatch'),
      e('⏲️', 'timer'),
      e('⏳', 'hourglass flowing'),
      e('⌛', 'hourglass done'),
      e('📡', 'satellite antenna'),
      e('📚', 'books'),
      e('📖', 'open book'),
      e('🔖', 'bookmark'),
      e('🏷️', 'tag'),
      e('📰', 'newspaper'),
      e('🗞️', 'rolled newspaper'),
      e('📄', 'page'),
      e('📃', 'page curl'),
      e('📑', 'bookmark tabs'),
      e('📜', 'scroll'),
      e('📋', 'clipboard'),
      e('📅', 'calendar'),
      e('📆', 'tear off calendar'),
      e('🗓️', 'spiral calendar'),
      e('📇', 'card index'),
      e('🗃️', 'card file box'),
      e('🗳️', 'ballot box'),
      e('🗄️', 'file cabinet'),
      e('📂', 'open folder'),
      e('📁', 'folder'),
      e('📊', 'bar chart'),
      e('📈', 'chart up'),
      e('📉', 'chart down'),
      e('📌', 'pushpin'),
      e('📍', 'round pushpin'),
      e('📎', 'paperclip'),
      e('🖇️', 'linked paperclips'),
      e('📏', 'straight ruler'),
      e('📐', 'triangular ruler'),
      e('✂️', 'scissors'),
      e('🖊️', 'pen'),
      e('🖋️', 'fountain pen'),
      e('✒️', 'black nib'),
      e('🖌️', 'paintbrush'),
      e('🖍️', 'crayon'),
      e('📝', 'memo', 'note'),
      e('✏️', 'pencil'),
      e('🔏', 'locked with pen'),
      e('🔐', 'locked with key'),
      e('🔒', 'locked'),
      e('🔓', 'unlocked'),
      e('🧿', 'amulet'),
      e('🪬', 'hamsa'),
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '❤️',
    emojis: [
      e('❤️', 'red heart'),
      e('🧡', 'orange heart'),
      e('💛', 'yellow heart'),
      e('💚', 'green heart'),
      e('💙', 'blue heart'),
      e('💜', 'purple heart'),
      e('🖤', 'black heart'),
      e('🤍', 'white heart'),
      e('🤎', 'brown heart'),
      e('💔', 'broken heart'),
      e('❣️', 'heart exclamation'),
      e('💕', 'two hearts'),
      e('💞', 'revolving hearts'),
      e('💓', 'beating heart'),
      e('💗', 'growing heart'),
      e('💖', 'sparkling heart'),
      e('💘', 'heart arrow'),
      e('💝', 'heart with ribbon'),
      e('💟', 'heart decoration'),
      e('☮️', 'peace'),
      e('✝️', 'cross'),
      e('☪️', 'star and crescent'),
      e('🕉️', 'om'),
      e('☸️', 'wheel of dharma'),
      e('✡️', 'star of david'),
      e('🔯', 'six pointed star'),
      e('🕎', 'menorah'),
      e('☯️', 'yin yang'),
      e('☦️', 'orthodox cross'),
      e('🛐', 'place of worship'),
      e('⛎', 'ophiuchus'),
      e('♈', 'aries'),
      e('♉', 'taurus'),
      e('♊', 'gemini'),
      e('♋', 'cancer'),
      e('♌', 'leo'),
      e('♍', 'virgo'),
      e('♎', 'libra'),
      e('♏', 'scorpio'),
      e('♐', 'sagittarius'),
      e('♑', 'capricorn'),
      e('♒', 'aquarius'),
      e('♓', 'pisces'),
      e('🆔', 'id'),
      e('⚛️', 'atom'),
      e('🉑', 'accept'),
      e('☢️', 'radioactive'),
      e('☣️', 'biohazard'),
      e('📴', 'phone off'),
      e('📳', 'vibration'),
      e('🈶', 'not free'),
      e('🈚', 'free'),
      e('🈸', 'application'),
      e('🈺', 'open for business'),
      e('🈷️', 'monthly amount'),
      e('✴️', 'eight pointed star'),
      e('🆚', 'vs'),
      e('💮', 'white flower'),
      e('🉐', 'bargain'),
      e('㊙️', 'secret'),
      e('㊗️', 'congratulations'),
      e('🈴', 'passing grade'),
      e('🈵', 'no vacancy'),
      e('🈹', 'discount'),
      e('🈲', 'prohibited'),
      e('🅰️', 'a button'),
      e('🅱️', 'b button'),
      e('🆎', 'ab button'),
      e('🆑', 'cl button'),
      e('🅾️', 'o button'),
      e('🆘', 'sos'),
      e('❌', 'cross mark'),
      e('⭕', 'circle'),
      e('🛑', 'stop sign'),
      e('⛔', 'no entry'),
      e('📛', 'name badge'),
      e('🚫', 'prohibited sign'),
      e('💯', '100', 'hundred'),
      e('💢', 'anger'),
      e('♨️', 'hot springs'),
      e('🚷', 'no pedestrians'),
      e('🚯', 'no littering'),
      e('🚳', 'no bicycles'),
      e('🚱', 'non potable'),
      e('🔞', 'no minors'),
      e('📵', 'no phones'),
      e('🚭', 'no smoking'),
      e('❗', 'exclamation'),
      e('❕', 'white exclamation'),
      e('❓', 'question'),
      e('❔', 'white question'),
      e('‼️', 'double exclamation'),
      e('⁉️', 'exclamation question'),
      e('🔅', 'dim'),
      e('🔆', 'bright'),
      e('〽️', 'part alternation'),
      e('⚠️', 'warning'),
      e('🚸', 'children crossing'),
      e('🔱', 'trident'),
      e('⚜️', 'fleur de lis'),
      e('🔰', 'beginner'),
      e('♻️', 'recycle'),
      e('✅', 'check mark'),
      e('🈯', 'reserved'),
      e('💹', 'chart with yen'),
      e('❇️', 'sparkle'),
      e('✳️', 'eight spoked asterisk'),
      e('❎', 'cross box'),
      e('🌐', 'globe meridians'),
      e('💠', 'diamond'),
      e('Ⓜ️', 'circled m'),
      e('🌀', 'cyclone'),
      e('💤', 'zzz', 'sleep'),
      e('🏧', 'atm'),
      e('🚾', 'water closet'),
      e('♿', 'wheelchair'),
      e('🅿️', 'parking'),
      e('🛗', 'elevator'),
      e('🈳', 'vacancy'),
      e('🈂️', 'service'),
      e('🛂', 'passport control'),
      e('🛃', 'customs'),
      e('🛄', 'baggage claim'),
      e('🛅', 'left luggage'),
      e('🚹', 'mens'),
      e('🚺', 'womens'),
      e('🚼', 'baby symbol'),
      e('🚻', 'restroom'),
      e('🚮', 'litter bin'),
      e('🎦', 'cinema'),
      e('📶', 'antenna bars'),
      e('🈁', 'here'),
      e('🔣', 'input symbols'),
      e('ℹ️', 'info'),
      e('🔤', 'input latin'),
      e('🔡', 'input lowercase'),
      e('🔠', 'input uppercase'),
      e('🆖', 'ng'),
      e('🆗', 'ok'),
      e('🆙', 'up'),
      e('🆒', 'cool'),
      e('🆕', 'new'),
      e('🆓', 'free'),
      e('0️⃣', 'keycap 0'),
      e('1️⃣', 'keycap 1'),
      e('2️⃣', 'keycap 2'),
      e('3️⃣', 'keycap 3'),
      e('4️⃣', 'keycap 4'),
      e('5️⃣', 'keycap 5'),
      e('6️⃣', 'keycap 6'),
      e('7️⃣', 'keycap 7'),
      e('8️⃣', 'keycap 8'),
      e('9️⃣', 'keycap 9'),
      e('🔟', 'keycap 10'),
      e('🔢', 'input numbers'),
      e('#️⃣', 'keycap hash'),
      e('*️⃣', 'keycap asterisk'),
      e('▶️', 'play'),
      e('⏸️', 'pause'),
      e('⏯️', 'play or pause'),
      e('⏹️', 'stop button'),
      e('⏺️', 'record'),
      e('⏭️', 'next track'),
      e('⏮️', 'last track'),
      e('⏩', 'fast forward'),
      e('⏪', 'fast reverse'),
      e('⏫', 'fast up'),
      e('⏬', 'fast down'),
      e('◀️', 'reverse'),
      e('🔼', 'up button'),
      e('🔽', 'down button'),
      e('➡️', 'right arrow'),
      e('⬅️', 'left arrow'),
      e('⬆️', 'up arrow'),
      e('⬇️', 'down arrow'),
      e('↗️', 'up right arrow'),
      e('↘️', 'down right arrow'),
      e('↙️', 'down left arrow'),
      e('↖️', 'up left arrow'),
      e('↕️', 'up down arrow'),
      e('↔️', 'left right arrow'),
      e('↪️', 'right arrow curving'),
      e('↩️', 'left arrow curving'),
      e('⤴️', 'arrow up curve'),
      e('⤵️', 'arrow down curve'),
      e('🔀', 'shuffle'),
      e('🔁', 'repeat'),
      e('🔂', 'repeat single'),
      e('🔄', 'arrows ccw'),
      e('🔃', 'arrows cw'),
      e('🎵', 'note'),
      e('🎶', 'notes'),
      e('➕', 'plus'),
      e('➖', 'minus'),
      e('➗', 'divide'),
      e('✖️', 'multiply'),
      e('🟰', 'equals'),
      e('♾️', 'infinity'),
      e('💲', 'dollar'),
      e('💱', 'currency exchange'),
      e('™️', 'tm'),
      e('©️', 'copyright'),
      e('®️', 'registered'),
      e('〰️', 'wavy'),
      e('➰', 'curly loop'),
      e('➿', 'double curly loop'),
      e('🔚', 'end'),
      e('🔙', 'back'),
      e('🔛', 'on'),
      e('🔝', 'top'),
      e('🔜', 'soon'),
      e('✔️', 'check'),
      e('☑️', 'ballot box check'),
      e('🔘', 'radio button'),
      e('🔴', 'red circle'),
      e('🟠', 'orange circle'),
      e('🟡', 'yellow circle'),
      e('🟢', 'green circle'),
      e('🔵', 'blue circle'),
      e('🟣', 'purple circle'),
      e('🟤', 'brown circle'),
      e('⚫', 'black circle'),
      e('⚪', 'white circle'),
      e('🟥', 'red square'),
      e('🟧', 'orange square'),
      e('🟨', 'yellow square'),
      e('🟩', 'green square'),
      e('🟦', 'blue square'),
      e('🟪', 'purple square'),
      e('🟫', 'brown square'),
      e('⬛', 'black square'),
      e('⬜', 'white square'),
      e('◼️', 'medium black square'),
      e('◻️', 'medium white square'),
      e('◾', 'small black square'),
      e('◽', 'small white square'),
      e('▪️', 'tiny black square'),
      e('▫️', 'tiny white square'),
      e('🔶', 'large orange diamond'),
      e('🔷', 'large blue diamond'),
      e('🔸', 'small orange diamond'),
      e('🔹', 'small blue diamond'),
      e('🔺', 'red triangle up'),
      e('🔻', 'red triangle down'),
      e('🔳', 'white square button'),
      e('🔲', 'black square button'),
    ],
  },
  {
    id: 'flags',
    label: 'Flags',
    icon: '🏳️',
    emojis: [
      e('🏁', 'checkered flag'),
      e('🚩', 'triangular flag'),
      e('🎌', 'crossed flags'),
      e('🏴', 'black flag'),
      e('🏳️', 'white flag'),
      e('🏳️‍🌈', 'rainbow flag'),
      e('🏳️‍⚧️', 'transgender flag'),
      e('🏴‍☠️', 'pirate flag'),
      e('🇺🇸', 'united states', 'us', 'usa'),
      e('🇨🇦', 'canada'),
      e('🇲🇽', 'mexico'),
      e('🇬🇧', 'united kingdom', 'uk'),
      e('🇮🇪', 'ireland'),
      e('🇫🇷', 'france'),
      e('🇩🇪', 'germany'),
      e('🇮🇹', 'italy'),
      e('🇪🇸', 'spain'),
      e('🇵🇹', 'portugal'),
      e('🇳🇱', 'netherlands'),
      e('🇧🇪', 'belgium'),
      e('🇨🇭', 'switzerland'),
      e('🇦🇹', 'austria'),
      e('🇸🇪', 'sweden'),
      e('🇳🇴', 'norway'),
      e('🇩🇰', 'denmark'),
      e('🇫🇮', 'finland'),
      e('🇮🇸', 'iceland'),
      e('🇵🇱', 'poland'),
      e('🇨🇿', 'czech republic'),
      e('🇸🇰', 'slovakia'),
      e('🇭🇺', 'hungary'),
      e('🇷🇴', 'romania'),
      e('🇧🇬', 'bulgaria'),
      e('🇬🇷', 'greece'),
      e('🇹🇷', 'turkey'),
      e('🇷🇺', 'russia'),
      e('🇺🇦', 'ukraine'),
      e('🇨🇳', 'china'),
      e('🇯🇵', 'japan'),
      e('🇰🇷', 'south korea', 'korea'),
      e('🇮🇳', 'india'),
      e('🇵🇰', 'pakistan'),
      e('🇧🇩', 'bangladesh'),
      e('🇹🇭', 'thailand'),
      e('🇻🇳', 'vietnam'),
      e('🇮🇩', 'indonesia'),
      e('🇵🇭', 'philippines'),
      e('🇲🇾', 'malaysia'),
      e('🇸🇬', 'singapore'),
      e('🇦🇺', 'australia'),
      e('🇳🇿', 'new zealand'),
      e('🇧🇷', 'brazil'),
      e('🇦🇷', 'argentina'),
      e('🇨🇱', 'chile'),
      e('🇨🇴', 'colombia'),
      e('🇵🇪', 'peru'),
      e('🇻🇪', 'venezuela'),
      e('🇿🇦', 'south africa'),
      e('🇪🇬', 'egypt'),
      e('🇲🇦', 'morocco'),
      e('🇰🇪', 'kenya'),
      e('🇳🇬', 'nigeria'),
      e('🇸🇦', 'saudi arabia'),
      e('🇦🇪', 'uae'),
      e('🇮🇱', 'israel'),
      e('🇮🇷', 'iran'),
      e('🇮🇶', 'iraq'),
      e('🇸🇾', 'syria'),
      e('🇱🇧', 'lebanon'),
      e('🇯🇴', 'jordan'),
      e('🇪🇺', 'european union', 'eu'),
      e('🇺🇳', 'united nations', 'un'),
    ],
  },
];

/**
 * Flat list of every emoji across all categories — used as the search
 * corpus and to expose a `getEmojiByChar` lookup.
 */
export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);

/** Search for emoji whose name or keywords contain the query (case-insensitive). */
export function searchEmojis(query: string, limit = 80): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: EmojiEntry[] = [];
  for (const entry of ALL_EMOJIS) {
    if (entry.keywords.includes(q)) {
      out.push(entry);
      if (out.length >= limit) break;
    }
  }
  return out;
}

// ── Unified picker entries (emoji + FontAwesome icons) ─────────────

import { ICONS } from '@bendyline/squisq/icons';
import { canonicalIconToken } from '@bendyline/squisq/icons';
import type { IconEntry, IconFamily } from '@bendyline/squisq/icons';

/**
 * Discriminated picker entry. The picker UI dispatches on `kind` to
 * render either an emoji glyph or a FontAwesome `<i>` element. The
 * Toolbar consumes the selected entry to insert into the editor.
 */
export type PickerEntry =
  | { kind: 'emoji'; char: string; name: string; keywords: string }
  | {
      kind: 'icon';
      family: IconFamily;
      name: string;
      label: string;
      keywords: string;
      /** Canonical token used in the markdown source (bare or qualified). */
      token: string;
    };

export interface PickerCategory {
  id: string;
  label: string;
  /** What to render on the category tab. Emoji glyph or FA class. */
  tab: { kind: 'emoji'; char: string } | { kind: 'icon'; family: IconFamily; name: string };
  entries: PickerEntry[];
}

function buildIconCategory(family: IconFamily, label: string): PickerCategory {
  // Pick a representative icon for the tab — `github` for brands, `house` for solid,
  // `face-smile` for regular. We fall back to the family's first entry if the
  // representative is missing in a future FA version.
  const repName = family === 'brands' ? 'github' : family === 'solid' ? 'house' : 'face-smile';
  const familyIcons = ICONS.filter((i) => i.family === family);
  const rep = familyIcons.find((i) => i.name === repName) ?? familyIcons[0];
  const tabIcon = rep
    ? { kind: 'icon' as const, family, name: rep.name }
    : { kind: 'emoji' as const, char: '◆' };
  return {
    id: `fa-${family}`,
    label,
    tab: tabIcon,
    entries: familyIcons.map(
      (i: IconEntry): PickerEntry => ({
        kind: 'icon',
        family: i.family,
        name: i.name,
        label: i.label,
        keywords: i.keywords,
        token: canonicalIconToken(i),
      }),
    ),
  };
}

/**
 * The full picker category list — emoji buckets followed by the three
 * FontAwesome families. Drives the EmojiPicker tabs.
 */
export const PICKER_CATEGORIES: PickerCategory[] = [
  ...EMOJI_CATEGORIES.map(
    (c): PickerCategory => ({
      id: c.id,
      label: c.label,
      tab: { kind: 'emoji', char: c.icon },
      entries: c.emojis.map(
        (e): PickerEntry => ({
          kind: 'emoji',
          char: e.char,
          name: e.name,
          keywords: e.keywords,
        }),
      ),
    }),
  ),
  buildIconCategory('brands', 'Brands'),
  buildIconCategory('solid', 'Solid'),
  buildIconCategory('regular', 'Regular'),
];

/** Flat corpus for the picker search index. */
export const ALL_PICKER_ENTRIES: PickerEntry[] = PICKER_CATEGORIES.flatMap((c) => c.entries);

/** Lowercase substring search across emoji + icon entries. */
export function searchPickerEntries(query: string, limit = 80): PickerEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const out: PickerEntry[] = [];
  for (const entry of ALL_PICKER_ENTRIES) {
    if (entry.keywords.includes(q)) {
      out.push(entry);
      if (out.length >= limit) break;
    }
  }
  return out;
}
