import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { DocPlayer } from '../DocPlayer';
import type { Doc } from '@bendyline/squisq/schemas';
import type { AudioController } from '../hooks/AudioController';
import type { SquisqRenderAPI } from '../types';

function minimalDoc(): Doc {
  return {
    articleId: 'smoke',
    duration: 5,
    blocks: [{ id: 'b1', startTime: 0, duration: 5, audioSegment: 0, layers: [] }],
    audio: { segments: [] },
  };
}

function docWithCover(): Doc {
  return {
    ...minimalDoc(),
    startBlock: {
      title: 'Managed Cover',
      subtitle: 'Generated by Squisq',
    },
  };
}

function controller(overrides: Partial<AudioController> = {}): AudioController {
  return {
    currentTime: 0,
    isPlaying: false,
    currentSegment: 0,
    totalDuration: 5,
    isEnded: false,
    isReady: true,
    isAvailable: true,
    play: vi.fn(async () => {}),
    pause: vi.fn(async () => {}),
    toggle: vi.fn(async () => {}),
    seekTo: vi.fn(async () => {}),
    skipToSegment: vi.fn(async () => {}),
    restart: vi.fn(async () => {}),
    ...overrides,
  };
}

describe('DocPlayer smoke test', () => {
  beforeAll(() => {
    vi.spyOn(window.HTMLMediaElement.prototype, 'pause').mockImplementation(() => {});
  });

  afterAll(() => {
    vi.restoreAllMocks();
  });

  it('renders without crashing in video mode (default)', () => {
    const { container } = render(<DocPlayer doc={minimalDoc()} basePath="/test" />);
    expect(container.firstChild).toBeTruthy();
  });

  it('renders without crashing in slideshow mode', () => {
    const { container } = render(
      <DocPlayer doc={minimalDoc()} basePath="/test" displayMode="slideshow" />,
    );
    expect(container.firstChild).toBeTruthy();
  });

  it('shows the managed cover as the first slideshow entry by default', async () => {
    const { container } = render(
      <DocPlayer doc={docWithCover()} basePath="/test" displayMode="slideshow" />,
    );
    await waitFor(() => expect(container.textContent).toContain('Managed Cover'));
    expect(screen.getByTestId('slide-counter').textContent).toBe('Cover');
  });

  it('can suppress the managed cover slide', () => {
    const { container } = render(
      <DocPlayer
        doc={docWithCover()}
        basePath="/test"
        displayMode="slideshow"
        showCoverSlide={false}
      />,
    );
    expect(container.textContent).not.toContain('Managed Cover');
    expect(screen.getByTestId('slide-counter').textContent).toBe('1 / 1');
  });

  it('advances from slideshow cover to slide 1', async () => {
    const { container } = render(
      <DocPlayer doc={docWithCover()} basePath="/test" displayMode="slideshow" />,
    );
    await waitFor(() => expect(screen.getByTestId('slide-counter').textContent).toBe('Cover'));
    fireEvent.click(screen.getByTestId('slide-next'));
    await waitFor(() => expect(screen.getByTestId('slide-counter').textContent).toBe('1 / 1'));
    expect(container.textContent).not.toContain('Managed Cover');
  });

  it('reinitializes cover state when a new document replaces the old one', async () => {
    const { container, rerender } = render(
      <DocPlayer doc={docWithCover()} basePath="/test" displayMode="slideshow" />,
    );
    fireEvent.click(screen.getByTestId('slide-next'));
    await waitFor(() => expect(screen.getByTestId('slide-counter').textContent).toBe('1 / 1'));
    rerender(
      <DocPlayer
        doc={{
          ...docWithCover(),
          articleId: 'replacement',
          startBlock: { title: 'Replacement Cover' },
        }}
        basePath="/test"
        displayMode="slideshow"
      />,
    );
    await waitFor(() => expect(container.textContent).toContain('Replacement Cover'));
    expect(screen.getByTestId('slide-counter').textContent).toBe('Cover');
  });

  it('renders without crashing in linear mode', () => {
    const { container } = render(
      <DocPlayer doc={minimalDoc()} basePath="/test" displayMode="linear" />,
    );
    expect(container.firstChild).toBeTruthy();
  });

  it('exposes playback controls via onControlsReady', () => {
    let controls: { play: () => void; pause: () => void } | null = null;
    render(
      <DocPlayer
        doc={minimalDoc()}
        basePath="/test"
        showControls={false}
        onControlsReady={(c) => {
          controls = c;
        }}
      />,
    );
    expect(controls).not.toBeNull();
    expect(typeof controls!.play).toBe('function');
    expect(typeof controls!.pause).toBe('function');
  });

  it('handles keyboard shortcuts only in the focused player instance', () => {
    const first = controller();
    const second = controller();
    const { container } = render(
      <>
        <DocPlayer doc={minimalDoc()} audioController={first} showControls={false} />
        <DocPlayer doc={minimalDoc()} audioController={second} showControls={false} />
      </>,
    );
    const players = container.querySelectorAll<HTMLElement>('.doc-player');
    players[1].focus();
    fireEvent.keyDown(players[1], { key: ' ' });
    expect(second.toggle).toHaveBeenCalledOnce();
    expect(first.toggle).not.toHaveBeenCalled();

    const editable = document.createElement('div');
    editable.setAttribute('contenteditable', 'true');
    players[1].append(editable);
    fireEvent.keyDown(editable, { key: ' ' });
    expect(second.toggle).toHaveBeenCalledOnce();
  });

  it('keeps render APIs scoped to their player callbacks during sibling cleanup', () => {
    const firstEvents: Array<SquisqRenderAPI | null> = [];
    const secondEvents: Array<SquisqRenderAPI | null> = [];
    const one = render(
      <DocPlayer
        doc={minimalDoc()}
        renderMode
        audioController={controller()}
        onRenderAPIReady={(api) => firstEvents.push(api)}
      />,
    );
    render(
      <DocPlayer
        doc={minimalDoc()}
        renderMode
        audioController={controller()}
        onRenderAPIReady={(api) => secondEvents.push(api)}
      />,
    );
    const secondAPI = secondEvents[secondEvents.length - 1];
    expect(firstEvents[firstEvents.length - 1]).not.toBeNull();
    expect(secondAPI).not.toBeNull();

    one.unmount();

    expect(firstEvents[firstEvents.length - 1]).toBeNull();
    expect(secondEvents[secondEvents.length - 1]).toBe(secondAPI);
    expect(typeof secondAPI?.seekTo).toBe('function');
    expect('seekTo' in window).toBe(false);
    expect('getDuration' in window).toBe(false);
    expect('squisqActivePlayerId' in window).toBe(false);
    expect('squisqPlayers' in window).toBe(false);
  });

  it('delivers and cleans up an instance render API through the callback', () => {
    const observed: Array<SquisqRenderAPI | null> = [];
    const { unmount } = render(
      <DocPlayer
        doc={minimalDoc()}
        renderMode
        audioController={controller()}
        onRenderAPIReady={(api) => observed.push(api)}
      />,
    );

    expect(observed[observed.length - 1]?.getDuration()).toBeGreaterThan(0);
    unmount();
    expect(observed[observed.length - 1]).toBeNull();
  });

  it('keeps the render API identity stable while dispatching to the latest controller', async () => {
    const firstController = controller({ currentSegment: 0 });
    const secondController = controller({ currentSegment: 1 });
    const observed: Array<SquisqRenderAPI | null> = [];
    const onRenderAPIReady = (api: SquisqRenderAPI | null) => observed.push(api);
    const { rerender } = render(
      <DocPlayer
        doc={minimalDoc()}
        renderMode
        audioController={firstController}
        onRenderAPIReady={onRenderAPIReady}
      />,
    );
    const api = observed[observed.length - 1];
    expect(api).not.toBeNull();

    rerender(
      <DocPlayer
        doc={minimalDoc()}
        renderMode
        audioController={secondController}
        onRenderAPIReady={onRenderAPIReady}
      />,
    );

    expect(observed[observed.length - 1]).toBe(api);
    await api!.seekTo(3.25);
    expect(secondController.seekTo).toHaveBeenCalledWith(3.25);
    expect(firstController.seekTo).not.toHaveBeenCalled();
  });

  it('refreshes instance render metadata when the doc prop changes', () => {
    const firstDoc: Doc = { ...minimalDoc(), captions: { version: 1, phrases: [] } };
    const observed: Array<SquisqRenderAPI | null> = [];
    const onRenderAPIReady = (next: SquisqRenderAPI | null) => {
      observed.push(next);
    };
    const { container, rerender } = render(
      <DocPlayer
        doc={firstDoc}
        renderMode
        audioController={controller()}
        onRenderAPIReady={onRenderAPIReady}
      />,
    );
    expect(container.querySelector('.doc-player')).toBeTruthy();
    const nextDoc: Doc = {
      ...minimalDoc(),
      captions: {
        version: 1,
        phrases: [{ text: 'new caption', startTime: 0, endTime: 1, audioSegment: 0 }],
      },
    };
    rerender(
      <DocPlayer
        doc={nextDoc}
        renderMode
        audioController={controller()}
        onRenderAPIReady={onRenderAPIReady}
      />,
    );
    expect(observed[observed.length - 1]?.getCaptions()).toEqual([
      { text: 'new caption', startTime: 0, endTime: 1 },
    ]);
  });
});

describe('DocPlayer front door (doc / markdown resolution)', () => {
  it('renders a doc built from the markdown prop', () => {
    const { container } = render(
      <DocPlayer markdown={'# Hello From Markdown\n\nBody text here.'} displayMode="linear" />,
    );
    expect(container.querySelector('.doc-player')).toBeTruthy();
    expect(container.textContent).toContain('Hello From Markdown');
  });

  it('doc wins over markdown when both are provided', () => {
    const { container } = render(
      <DocPlayer doc={minimalDoc()} markdown="# Markdown Loses" displayMode="linear" />,
    );
    expect(container.querySelector('.doc-player')).toBeTruthy();
    expect(container.textContent).not.toContain('Markdown Loses');
  });

  it('renders an empty state without throwing when neither doc nor markdown is given', () => {
    const { container } = render(<DocPlayer />);
    const empty = container.querySelector('.doc-player--empty');
    expect(empty).toBeTruthy();
    expect(empty!.classList.contains('doc-player')).toBe(true);
  });

  it('defaults basePath when omitted', () => {
    const { container } = render(<DocPlayer doc={minimalDoc()} />);
    expect(container.querySelector('.doc-player')).toBeTruthy();
  });
});
